fos_rest:
    view:
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        view_response_listener: 'force'
    body_converter:
        enabled: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api/v1', priorities: ['json '], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    exception:
        enabled: true